<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "    <head>\n";
echo "        <meta charset=\"UTF-8\">\n";
echo "        <meta name=\"viewport\"\n";
echo "        content=\"width=derice-width, inicial-scale=1.0\">\n";
echo "        <title>Portafolio: Karime Lizeth Sánchez Ortega</title>\n";
echo "        <link rel=\"stylesheet\" href=\"index.css\">\n";
echo "    </head>\n";
echo "    <body>\n";
echo "        <div id=\"contenedor\">\n";
echo "            <header>\n";
echo "                <div class=\"imag\" id=\"titulo\">\n";
echo "                    <br> <br>\n";
echo "                    <h1>\n";
echo "                        PORTAFOLIO:\n";
echo "                    </h1>\n";
echo "                    <h1>\n";
echo "                        Karime Lizeth Sánchez Ortega\n";
echo "                    </h1>\n";
echo "                    <br> <br> <br>\n";
echo "                </div>\n";
echo "            </header>\n";
echo "            <selection>\n";
echo "                <article>\n";
echo "                    <div id=\"margen\">\n";
echo "                        <br>\n";
echo "                        <br>\n";
echo "                        <h2>\n";
echo "                            Sobre mi\n";
echo "                        </h2>\n";
echo "                        <p>\n";
echo "                            Estudiante de la Universidad Politécnica de Lázaro Cárdenas (UPLC), en la carrera de Ing. Software.\n";
echo "                        </p>\n";
echo "                        <p>\n";
echo "                            Mi objetivo es dominar los lenguajes de C++, Java, HTML y Python que he aprendido durante cuando me enseñaron a programar.\n";
echo "                            Explorar nuevos conocimientoa, investigar muchas fuentes y saber como ejecutar lo que he aprendido en la zona laboral.\n";
echo "                        </p>\n";
echo "                        \n";
echo "                    </div>\n";
echo "                </article>\n";
echo "                <br>\n";
echo "                <aside>\n";
echo "                    <center>\n";
echo "                    <br> <br> <br> <br>\n";
echo "                    <div class=\"box\">\n";
echo "                    </div>\n";
echo "                    <br>\n";
echo "                    <img src=\"IMG/yo.png\" width=\"150px\">\n";
echo "                    <div class=\"box\">\n";
echo "                    </div>\n";
echo "                    </center>\n";
echo "                </aside>\n";
echo "            </selection>\n";
echo "            <br>\n";
echo "            <div class=\"linea\"></div>\n";
echo "            <br>\n";
echo "        </div>\n";
echo "        <nav>\n";
echo "            <div id=\"margen\">\n";
echo "                <h2>Programación Web</h2>\n";
echo "                <p id=\"pp\">\n";
echo "                    Ing. Andrés Luna Jaimes\n";
echo "                </p>\n";
echo "                <p>\n";
echo "                    Primero definamos qué es la programación web. Se trata del proceso por el cual desarrollas y diseñas una página web. Al igual que en la programación tradicional, para crear una web se utilizan una serie de lenguajes que te permiten dar forma al proyecto que quieres levantar. \n";
echo "                </p>\n";
echo "                <p>\n";
echo "                    Los lenguajes de programación web se caracterizan porque te dan la posibilidad de enlazar a través de hipervínculos a otros sitios para mejorar el posicionamiento y la calidad del contenido que le muestras al usuario. \n";
echo "                </p>\n";
echo "                <a href=\"https://www.thepowermba.com/es/blog/que-es-la-programacion-web\">Fuente...</a>\n";
echo "                \n";
echo "            </div>\n";
echo "        </nav>\n";
echo "        <footer>\n";
echo "            <div id=\"margen\">\n";
echo "                <center>\n";
echo "                    <a href=\"Unidad 01.php\"><button class=\"btn\">Unidad 1</button></a> \n";
echo "                    <a href=\"Unidad 02.php\"><button class=\"btn\">Unidad 2</button></a>\n";
echo "                    <a href=\"Unidad 03.php\"> <button class=\"btn\">Unidad 3</button></a>\n";
echo "                </center>\n";
echo "                \n";
echo "            </div>\n";
echo "        </footer>\n";
echo "    </body>\n";
echo "</html>\n";
?>