<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "    <head>\n";
echo "        <meta charset=\"UTF-8\">\n";
echo "        <meta name=\"viewport\"\n";
echo "        content=\"width=derice-width, inicial-scale=1.0\">\n";
echo "        <title>Portafolio: Karime Lizeth Sánchez Ortega</title>\n";
echo "        <link rel=\"stylesheet\" href=\"index.css\">\n";
echo "    </head>\n";
echo "    <body>\n";
echo "        <div id=\"margen\">\n";
echo "            <div>\n";
echo "                <a href=\"Portafolio.php\">\n";
echo "                    <img src=\"IMG/flecha.png\" class=\"elemento\">\n";
echo "                </a>\n";
echo "            </div>\n";
echo "            \n";
echo "            <div>\n";
echo "                <ol>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/01_MediaQueries_KarimeS.html\">\n";
echo "                            MediaQueries\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/02_Actividad 01_Acerca de mi_KarimeS.html\">\n";
echo "                            Acerca de mi\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/03_01_JavaScript_KarimeS.html\">\n";
echo "                            JavaScript\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/03_02_HolaMundo!_KarimeS.html\">\n";
echo "                            Hola Mundo!\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/03_03_Alerta_KarimeS.html\">\n";
echo "                            Alerta\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/04_Actividad 02_Alerta (Nombre y Edad)_KarimeS.html\">\n";
echo "                            Alerta: Nombre y Edad\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/05_01_Operadores_KarimeS.html\">\n";
echo "                            Operadores\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/05_02_Estructuras de Control_KarimeS.html\">\n";
echo "                            Estructuras de Control\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/05_03_Funciones_KarimeS.html\">\n";
echo "                            Funciones\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/06_Generar Color Aleatorio_KarimeS.html\">\n";
echo "                            Generar Color Aleatorio\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/07 y 09_Bocho_KarimeS/07_Bocho_KarimeS.html\">\n";
echo "                            Bocho\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/08_Pagina de Personajes_KarimeS/08_Pagina de Personajes_KarimeS.html\">\n";
echo "                            Pagina de Personajes\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/07 y 09_Bocho_KarimeS/09_Bocho02_KarimeS.html\">\n";
echo "                            Bocho en lista\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/10_Foco_KarimeS/10_Foco_KarimeS.html\">\n";
echo "                            Foco\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/11 y 12_Loteria_KarimeS/11_Loteria_KarimeS.html\">\n";
echo "                            Loteria\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/11 y 12_Loteria_KarimeS/12_Loteria con Arreglos_KarimeS.html\">\n";
echo "                            Loteria con arreglos\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 02/Examen Unidad 02_Karime Lizeth Sanchez Ortega.html\">\n";
echo "                            Examen Unidad 02\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                </ol>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </body>\n";
echo "</html>\n";
?>