<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "    <head>\n";
echo "        <meta charset=\"UTF-8\">\n";
echo "        <meta name=\"viewport\"\n";
echo "        content=\"width=derice-width, inicial-scale=1.0\">\n";
echo "        <title>Portafolio: Karime Lizeth Sánchez Ortega</title>\n";
echo "        <link rel=\"stylesheet\" href=\"index.css\">\n";
echo "    </head>\n";
echo "    <body>\n";
echo "        <div id=\"margen\">\n";
echo "            <div>\n";
echo "                <a href=\"Portafolio.php\">\n";
echo "                    <img src=\"IMG/flecha.png\" class=\"elemento\">\n";
echo "                </a>\n";
echo "            </div>\n";
echo "            <div>\n";
echo "                <ol>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 01/01_La guerra de los navegadores_KarimeS.html\">\n";
echo "                            La guerra de los navegadores\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 01/02_Formulario_KarimeS.html\">\n";
echo "                            Formulario\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 01/03_Formularios 2da parte_KarimeS.html\">\n";
echo "                            Formulario 2da parte\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 01/04_Color_KarimeS.html\">\n";
echo "                            Color\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 01/05_Menú con subMenú_KarimeS.html\">\n";
echo "                            Menú con Sub-menú\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 01/06_Tabla_KarimeS.html\">\n";
echo "                            Tabla\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 01/07_Contenedor_KarimeS.html\">\n";
echo "                            contenedor\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 01/08_Pagina Web 01_KarimeS.html\">\n";
echo "                            Página Web\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 01/09_Cuadro_KarimeS.html\">\n";
echo "                            Cuadro\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                    <li>\n";
echo "                        <a href=\"Unidad 01/Karime Lizeth Sanchez Ortega (Examen) U1 IS/index.html\">\n";
echo "                            Examen Unidad 01\n";
echo "                        </a>\n";
echo "                    </li>\n";
echo "                </ol>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </body>\n";
echo "</html>\n";
?>